import type{ Client, Prospect, MembreEquipe } from "../types";

export const SEED_CLIENTS: Client[] = [
  {
    id: 1,
    nom: "Mensah",
    prenom: "Kofi Emmanuel",
    tel: "+225 07 12 34 56",
    email: "kofi.mensah@gmail.com",
    adresse: "Cocody Riviera, Abidjan",
    profession: "Commerçant",
    observations: "Client fidèle depuis 2019. Préfère les appels le matin.",
    contrats: [
      {
        id: "AUTO-2026-0342",
        type: "Auto",
        numero: "AUTO-2026-0342",
        echeance: "2026-06-25",
        statut: "Actif",
        prime: 185000,
        detail: "Toyota Corolla 2020",
      },
      {
        id: "SANT-2026-1205",
        type: "Santé",
        numero: "SANT-2026-1205",
        echeance: "2026-12-30",
        statut: "Actif",
        prime: 240000,
      },
    ],
    relances: [
      {
        date: "2026-06-15",
        type: "Appel",
        note: "Rappelé pour renouvellement Auto. Client intéressé.",
        resultat: "Positif",
      },
      {
        date: "2026-05-20",
        type: "SMS",
        note: "Envoyé rappel échéance Auto.",
        resultat: "Envoyé",
      },
    ],
  },
  {
    id: 2,
    nom: "Diallo",
    prenom: "Amara",
    tel: "+221 77 234 56 78",
    email: "amara.diallo@hotmail.com",
    adresse: "Plateau, Dakar",
    profession: "Ingénieur",
    observations: "Intéressé par extension couverture santé famille.",
    contrats: [
      {
        id: "HAB-2025-0891",
        type: "Habitation",
        numero: "HAB-2025-0891",
        echeance: "2025-12-15",
        statut: "Expiré",
        prime: 95000,
      },
      {
        id: "SANT-2026-0445",
        type: "Santé",
        numero: "SANT-2026-0445",
        echeance: "2026-09-15",
        statut: "Actif",
        prime: 320000,
      },
    ],
    relances: [
      {
        date: "2026-06-20",
        type: "Appel",
        note: "Discussion renouvellement Habitation.",
        resultat: "À rappeler",
      },
    ],
  },
  {
    id: 3,
    nom: "Konaté",
    prenom: "Fatou",
    tel: "+225 05 67 89 01",
    email: "fatou.konate@gmail.com",
    adresse: "Yopougon, Abidjan",
    profession: "Enseignante",
    observations: "Budget limité. Préfère les formules familiales.",
    contrats: [
      {
        id: "SANT-2026-0789",
        type: "Santé",
        numero: "SANT-2026-0789",
        echeance: "2026-08-01",
        statut: "Actif",
        prime: 185000,
      },
      {
        id: "VIE-2026-0112",
        type: "Vie",
        numero: "VIE-2026-0112",
        echeance: "2026-11-30",
        statut: "En attente",
        prime: 45000,
      },
    ],
    relances: [],
  },
  {
    id: 4,
    nom: "Traoré",
    prenom: "Moussa",
    tel: "+223 76 543 21 09",
    email: "moussa.traore@yahoo.fr",
    adresse: "ACI 2000, Bamako",
    profession: "Chef d'entreprise",
    observations: "Flotte de 4 véhicules. Intéressé par contrat groupé.",
    contrats: [
      {
        id: "AUTO-2026-0567",
        type: "Auto",
        numero: "AUTO-2026-0567",
        echeance: "2026-10-15",
        statut: "Actif",
        prime: 450000,
        detail: "Flotte 4 véhicules",
      },
      {
        id: "RC-2026-0234",
        type: "RC Pro",
        numero: "RC-2026-0234",
        echeance: "2026-07-10",
        statut: "Actif",
        prime: 280000,
      },
    ],
    relances: [
      {
        date: "2026-06-18",
        type: "Appel",
        note: "Intéressé par assurance flotte.",
        resultat: "Positif",
      },
    ],
  },
  {
    id: 5,
    nom: "Bah",
    prenom: "Aissatou",
    tel: "+224 62 123 45 67",
    email: "aissatou.bah@gmail.com",
    adresse: "Kaloum, Conakry",
    profession: "Médecin",
    observations: "Cliente VIP. Couverture complète famille.",
    contrats: [
      {
        id: "SANT-2026-0999",
        type: "Santé",
        numero: "SANT-2026-0999",
        echeance: "2026-06-28",
        statut: "Actif",
        prime: 680000,
      },
      {
        id: "AUTO-2025-0788",
        type: "Auto",
        numero: "AUTO-2025-0788",
        echeance: "2025-11-30",
        statut: "Résilié",
        prime: 210000,
      },
    ],
    relances: [
      {
        date: "2026-06-21",
        type: "Appel",
        note: "Relance urgente - Santé expire dans 7 jours.",
        resultat: "En attente",
      },
    ],
  },
  {
    id: 6,
    nom: "Ouédraogo",
    prenom: "Seydou",
    tel: "+226 70 234 56 78",
    email: "seydou.ouedraogo@gmail.com",
    adresse: "Ouaga 2000, Ouagadougou",
    profession: "Fonctionnaire",
    observations: "Paiement mensuel préféré.",
    contrats: [
      {
        id: "HAB-2026-0445",
        type: "Habitation",
        numero: "HAB-2026-0445",
        echeance: "2026-12-15",
        statut: "Actif",
        prime: 72000,
      },
    ],
    relances: [],
  },
  {
    id: 7,
    nom: "N'Diaye",
    prenom: "Cheikh",
    tel: "+221 76 567 89 01",
    email: "cheikh.ndiaye@orange.sn",
    adresse: "Almadies, Dakar",
    profession: "Architecte",
    observations: "Référé par Amara Diallo.",
    contrats: [
      {
        id: "AUTO-2026-0890",
        type: "Auto",
        numero: "AUTO-2026-0890",
        echeance: "2026-09-30",
        statut: "Actif",
        prime: 195000,
      },
    ],
    relances: [],
  },
  {
    id: 8,
    nom: "Coulibaly",
    prenom: "Mariam",
    tel: "+225 01 345 67 89",
    email: "mariam.coulibaly@gmail.com",
    adresse: "Marcory, Abidjan",
    profession: "Commerçante",
    observations: "À contacter pour renouvellement.",
    contrats: [
      {
        id: "AUTO-2025-1234",
        type: "Auto",
        numero: "AUTO-2025-1234",
        echeance: "2026-01-20",
        statut: "Expiré",
        prime: 155000,
      },
      {
        id: "SANT-2026-0678",
        type: "Santé",
        numero: "SANT-2026-0678",
        echeance: "2026-06-30",
        statut: "Actif",
        prime: 210000,
      },
    ],
    relances: [
      {
        date: "2026-06-21",
        type: "SMS",
        note: "Rappel - Santé expire dans 9 jours.",
        resultat: "Envoyé",
      },
    ],
  },
];

export const SEED_PROSPECTS: Prospect[] = [
  {
    id: 1,
    nom: "Sow Ibrahim",
    tel: "+221 77 890 12 34",
    source: "Référence",
    interet: "Auto",
    statut: "Chaud",
    rdv: "2026-06-23",
    note: "Référé par Kofi Mensah. Budget 200k FCFA.",
  },
  {
    id: 2,
    nom: "Akosua Asante",
    tel: "+233 24 567 89 01",
    source: "Réseaux sociaux",
    interet: "Santé",
    statut: "Tiède",
    rdv: null,
    note: "A commenté la publication sur la mutuelle famille.",
  },
  {
    id: 3,
    nom: "Lamine Camara",
    tel: "+224 62 234 56 78",
    source: "Démarchage",
    interet: "Habitation",
    statut: "Froid",
    rdv: null,
    note: "Pas rappelé depuis 3 semaines.",
  },
  {
    id: 4,
    nom: "Adjoa Mensah",
    tel: "+225 07 456 78 90",
    source: "Référence",
    interet: "Vie",
    statut: "Chaud",
    rdv: "2026-06-24",
    note: "Veut assurance vie pour ses enfants.",
  },
  {
    id: 5,
    nom: "Boubacar Keita",
    tel: "+223 76 789 01 23",
    source: "Site web",
    interet: "RC Pro",
    statut: "Tiède",
    rdv: "2026-06-26",
    note: "Chef PME. Cherche couverture responsabilité.",
  },
  {
    id: 6,
    nom: "Ama Owusu",
    tel: "+233 20 345 67 89",
    source: "Événement",
    interet: "Auto",
    statut: "Froid",
    rdv: null,
    note: "Rencontrée au salon financier d'Accra.",
  },
];

export const EQUIPE: MembreEquipe[] = [
  { id: 1, nom: "Diop Ibrahima", role: "Producteur", clients: 45, contratsActifs: 62, relancesRetard: 3, conversion: 78 },
  { id: 2, nom: "Tanoh Sandrine", role: "Producteur", clients: 38, contratsActifs: 51, relancesRetard: 1, conversion: 82 },
  { id: 3, nom: "Konaré Moussa", role: "Commercial", clients: 12, contratsActifs: 28, relancesRetard: 5, conversion: 65 },
  { id: 4, nom: "Bamba Fatoumata", role: "Producteur", clients: 29, contratsActifs: 40, relancesRetard: 0, conversion: 91 },
];